---
galaxy_info:
  author: Cameron Rosier
  description: Installs Prometheus Monitoring Server

  license: Apache

  min_ansible_version: 2.0

  platforms:
    - name: Ubuntu Instance
      image: "ubuntu:18.04"

  galaxy_tags: []

dependencies: []
