---
# Change the version here for an upgrade or downgrade
prometheus_version: "2.16.0"

# User running prometheus
prometheus_user: "prometheus"

# Base url
base_url: "http://localhost:9090"

base_dir: "/opt/prometheus"
data_dir: "/srv/data/prometheus"
console_dir: "/etc/prometheus/consoles"
console_lib_dir: "/etc/prometheus/console_libraries"

master_cfg_url: "https://raw.githubusercontent.com/clrosier/prometheus-config/master/prometheus.yml"  # yamllint disable-line rule:line-length
branch_cfg_url: "https://raw.githubusercontent.com/clrosier/prometheus-config/{{ branch }}/prometheus.yml"  # yamllint disable-line rule:line-length

reload_url: "{{ base_url }}/-/reload"

download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
data_retention_period: "30d"
